[CodeGen] multi-contract output
second-state/SOLL pull request #60
Opened 2020-12-17 07:23 UTC by jacky860226

2020-12-23 18:21 UTC, ibmibmibm requested changes

2020-12-24 07:54 UTC, ibmibmibm commented on lib/CodeGen/CodeGenAction.cpp
> +  std::vector<std::unique_ptr<llvm::LLVMContext>> LLVMContextCopy;
LLVMContext只能有一個，不應該開vector儲存copy

2020-12-24 07:54 UTC, ibmibmibm commented on lib/Frontend/FrontendAction.cpp
> +  ParseAST(CI, true);
CompilerInstance只能出現在FrontentAction，不應傳出去

2020-12-24 07:54 UTC, ibmibmibm commented on lib/Parse/ParseAST.cpp
> +void ParseAST(CompilerInstance &CI, bool PrintStats) {
CompilerInstance只能出現在FrontentAction，不應傳出去

2020-12-24 07:54 UTC, ibmibmibm commented on lib/CodeGen/CodeGenAction.cpp
> +  BackendConsumer(BackendAction Action, CompilerInstance &CI,
CompilerInstance只能出現在FrontentAction，不應傳到這裡

2020-12-24 07:54 UTC, ibmibmibm commented on lib/CodeGen/CodeGenAction.cpp
> +  return std::make_unique<BackendConsumer>(Action, CI, InFile);
BackendConsumer應只針對單一一個SourceUnit
多個SourceUnit應該有多個BackendConsumer，多個ASTConsumer

2020-12-28 15:22 UTC, jacky860226 commented on lib/Frontend/FrontendAction.cpp
> +  ParseAST(CI, true);
想請問可以將CompilerInstance的createOutputFile移動到其他地方?
因為OutputFile name在parse()完成之後才會得到

2021-01-04 08:12 UTC, ibmibmibm approved these changes

2021-01-04 08:30 UTC, hydai commented
@jacky860226 Please rebase to the latest master commit. So we can merge this PR. Thanks.

2021-01-04 18:23 UTC, jacky860226 commented
> @jacky860226 Please rebase to the latest master commit. So we can merge this PR. Thanks.

OK

2021-01-05 08:32 UTC, merged