[Sema] inheritance support
second-state/SOLL pull request #74
Opened 2021-02-17 14:30 UTC by LFsWang

Detail state : #59 

## Current bugs :
* `resolveVirtual()` is unimplemented. The function pointer of contract except the last is wrong.
  * Modify codegen is required for above. It will be implemented in next version
* The compatibility of two function is **not** checked.

2021-03-16 12:56 UTC, hydai requested changes
Please check the coding style before the PR is submitted.

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +        for (size_t i = 0; i < Idx.size(); ++i) {
`I`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +        NodeType next;
`Next`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +        for (size_t i = 0; i < Idx.size(); ++i) {
`I`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +  void addDirectedEdge(NodeType childContName, NodeType baseContName) {
First character should be uppercase

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +  bool generator(NodeType cont) {
`Cont`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto base : Bases[cont]) {
`Base`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    bool status = true;
`Status`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto &[cont, deg] : Indegree) {
`Cont`, `Deg`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +  std::vector<NodeType> getL(NodeType cont) const {
`Cont`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    auto res = L.find(cont);
`Res`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +  std::map<llvm::StringRef, ContractDeclType *> str2Cont;
`Str2Cont`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +      const std::map<llvm::StringRef, ContractDeclType *> &contMap,
`ContMap`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    auto base = CD.getBaseContracts();
`Base`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    auto base = CD.getBaseContracts();
Or `Bases`, because of the base contracts can be multiple.

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto &b : base) {
`Base`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto b : CD.getFuncs())
`Func`?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto b : CD.getBaseContracts()) {
`BaseContract` or `Base`. The variable should have a clear name.

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto b : CD.getFuncs()) {
`Func`?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto b : CD.getVars()) {
`Var`?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto f : CD.getSubNodes())
What does `f` mean?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +  InheritStatusVarResolver(ContractDecl *cont) : Cont(cont) {
`CD`?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto var : cont->getVars())
Should we use `Cont` instead of taking the value from the argument?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    for (auto var : cont->getFuncs())
`var` -> `Func`?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +      auto varPtr = VarDecls.find(I.getName());
`VarPtr`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +  for (auto cDecl : Child) {
Use `CD` or `ChildDecl`.

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    auto pDeclIt = std::find_if(BaseDecl.begin(), BaseDecl.end(),
Assuming this `p` stands for `parent`?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +                                [cDecl](const Decl *node) {
`Node`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +          // TODO: check compatiblity for both cont
Should we fire an alert to users?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +        bool allowed = false;
`Allowed`

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +  // todo: the order of the Decl is important?
The order of Decl is important I think.
The state variables will use the order in hashing their storage address in the ethereum storage, AFAIK.

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +  DeclInheritResolver DTR;
`DIR` ?

2021-03-16 12:56 UTC, hydai commented on lib/Sema/SemaResolveInherit.cpp
> +    // cerr << "resolveInherit error! abort" << endl;
Please emit an error here.

2021-03-16 12:56 UTC, hydai commented on include/soll/Basic/DiagnosticParseKinds.inc
> +DIAG(err_multioverrided_unsupport, CLASS_ERROR, (unsigned)diag::Severity::Error, "Multinherited overrided is not supported!", 0, false, 1)
`Multi-inherited`?

2021-03-16 12:56 UTC, hydai commented on include/soll/AST/Decl.h
> +  IdentifierPath(std::vector<std::string> path) : Path(std::move(path)) {}
`P` or something.

2021-03-16 12:56 UTC, hydai commented on include/soll/AST/Decl.h
> +  std::vector<IdentifierPath> overrides;
`Overrieds`

2021-03-16 12:56 UTC, hydai commented on include/soll/AST/Decl.h
> +  FunctionDecl *resolveVirtual(const ContractDecl &mostDerivedContract);
`MostDerivedContract`

2021-03-16 12:56 UTC, hydai commented on lib/AST/Decl.cpp
> +    const std::vector<ContractDecl *> &conts) {
`Conts` or `Contracts`

2021-03-16 12:56 UTC, hydai commented on lib/AST/Decl.cpp
> +void ContractDecl::setInheritNodes(const std::vector<Decl *> &nodes) {
`Nodes`

2021-03-16 12:56 UTC, hydai commented on lib/CodeGen/ModuleBuilder.cpp
> +      // TODO : Should we make a warning ?
Yes. We should raise a warning.

2021-03-16 12:56 UTC, hydai commented on lib/Parse/Parser.cpp
> +        // TODO : fatalParserError
Please raise an fatal error.

2021-03-16 12:56 UTC, hydai commented on lib/Parse/Parser.cpp
> +  ContractDecl::ContractKind kind;
`Kind`.

2021-03-16 12:56 UTC, hydai commented on lib/Parse/Parser.cpp
> +  bool abstract = false;
`Abstract`

2021-03-16 12:56 UTC, hydai commented on lib/Parse/Parser.cpp
> +    // TODO : Constructor args is unimplement
Please raise an error message here.

2021-03-17 14:45 UTC, LFsWang commented on include/soll/AST/Decl.h
> +  bool isCompleted();
It will check if all decls are implemented

2021-03-18 05:13 UTC, hydai requested changes

2021-03-23 08:47 UTC, hydai approved these changes
LGTM

2021-03-23 08:47 UTC, merged