Using For
second-state/SOLL pull request #81
Opened 2021-04-29 04:39 UTC by jacky860226

Using For

2021-05-06 05:14 UTC, hydai requested changes

2021-05-06 05:14 UTC, hydai commented on lib/Frontend/FrontendAction.cpp
> +           CI.getFrontendOpts().LibrariesAddressMaps, true);
We should wrap the `LibrariesAddressMaps` into `ASTContext` like `Language`.

2021-05-12 18:47 UTC, hydai approved these changes

2021-05-12 21:41 UTC, ibmibmibm commented on lib/Sema/SemaResolveType.cpp
> +  ContractDecl *&CurrentContract;
為什麼這邊要用reference?

2021-05-13 05:42 UTC, merged

2021-05-13 05:55 UTC, jacky860226 commented on lib/Sema/SemaResolveType.cpp
> +  ContractDecl *&CurrentContract;
CurrentContract是跟第478行DeclTypeResolver中的CurrentContract同步的
DeclTypeResolver會修改到CurrentContract但是TypeResolver並不會
所以要用reference