Function return struct
second-state/SOLL pull request #86
Opened 2021-05-24 16:07 UTC by jacky860226

fix the bug of function return a Struct.
prepare for function return a Tuple.

2021-06-10 05:53 UTC, hydai requested changes

2021-06-10 05:53 UTC, hydai commented on include/soll/AST/Type.h
> +    for (size_t i = 0; i < ElementIndex; ++i) {
`I`

2021-06-15 23:34 UTC, ibmibmibm requested changes

2021-06-15 23:34 UTC, ibmibmibm commented on include/soll/AST/TypePtr.h
> +extern TypePtr AddressTypePayablePtr;
這些不應該是global variable，應該放在ASTContext裡面

2021-06-15 23:34 UTC, ibmibmibm commented on include/soll/AST/Type.h
> +  std::vector<std::reference_wrapper<const TypePtr>> ReturnTypes;
為什麼不用`Type*`?

2021-06-15 23:34 UTC, ibmibmibm commented on lib/AST/TypePtr.cpp
> +    std::make_shared<AddressType>(StateMutability::Payable);
應該在ASTContext內

2021-06-16 07:45 UTC, jacky860226 commented on include/soll/AST/Type.h
> +  std::vector<std::reference_wrapper<const TypePtr>> ReturnTypes;
resolve UndefineType會更換到TypePtr的本體所以用reference包起來
Type*是從TypePtr.get()來的，.get()拿不到reference

2021-06-28 07:52 UTC, hydai approved these changes

2021-06-28 07:52 UTC, merged